from enum import Enum

class BOOSTER_TAGS(Enum):
    EUROPE = "Europe"
    NORTH_AMERICA = "North America"
    CARRIBEAN = "Carribean"
    SOUTH_AMERICA = "South America"
    AFRICA = "Africa"
    EAST_ASIA = "East Asia"
    SOUTHEAST_ASIA = "Southeast Asia"
    OTHER_ASIA = "Other Asia"
    ISLAND = "Island"
    OCEANIA = "Oceania"
    HOME = "Home"
    @classmethod
    def export_to(cls, namespace):
        namespace.update(cls.__members__)

BOOSTER_TAGS.export_to(globals())

COUNTRY_TIER = {
    "SS": [
        "France",
        "Spain",
        "United States",
        "China",
        "Italy",
        "Türkiye",
        "Mexico",
        "Thailand",
        "United Kingdom",
        "Germany",
    ],
    "S": [
        "Denmark",
        "Japan",
        "Greece",
        "Malaysia",
        "Portugal",
        "Russia",
        "Hong Kong",
        "Austria",
        "UAE",
        "Poland",
        "Netherlands",
        "Singapore",
        "Macao",
        "Vietnam",
        "India",
        "Saudi Arabia",
        "Republic of Korea",
        "Croatia",
        "Hungary",
        "Indonesia",
        "Czech Republic",
    ],
    "A": [
        "Ukraine",
        "Egypt",
        "Morrocco",
        "Romania",
        "Bulgaria",
        "Taiwan",
        "Belarus",
        "Switzerland",
        "South Africa",
        "Australia",
        "Tunisia",
        "Belgium",
        "Iran",
        "Kazakhstan",
        "Kyrgyzstan",
        "Philippines",
        "Argentina",
        "Uzbekistan",
        "Cambodia",
        "Dominican Republic",
        "Slovakia",
        "Brazil",
        "Albania",
        "Nigeria",
        "Georgia",
        "Sweden",
        "Laos",
        "Slovenia",
        "Israel",
        "Chile",
        "Jordan",
        "Peru",
        "Cuba",
        "Colombia",
        "Norway",
        "Cyprus",
        "New Zealand",
    ],
    "B": [
        "Bahrain",
        "Uruguay",
        "Estonia", 
        "Puerto Rico",
        "Costa Rica",
        "Andorra",
        "Finland",
        "Lithuania",
        "Azerbaijan"
        "Malta",
        "Jamaica",
        "Montenegro",
        "Oman",
        "Syria",
        "Algeria",
        "Zimbabwe",
        "Qatar",
        "Ecuador",
        "Cote d'Ivoire",
        "Mozambique",
        "Iceland",
        "Lebanon",
        "Latvia",
        "Sri Lanka",
        "Armenia",
        "Kenya",
        "Bahamas",
        "El Salvador",
        "Panama",
        "Guatemala",
        "Maldives",
        "Guam",
        "Rwanda",
        "Serbia",
        "Turks & Caicos (British Overseas Territory)",
        "Namibia",
        "Uganda",
        "Tanzania",
        "Mauritius",
        "Nicaragua",
        "Tajikistan",
        "Bolivia",
        "Paraguay",
        "Bosnia & Herzegovinia",
        "Nepal",
        "Eswatini",
        "Lesotho",
        "Aruba (Constituent Country of the Kingdom of the Netherlands)",
        "Ghana",
        "Luxembourg",
        "Fiji",
        "Togo",
        "Cabo Verde",
        "Monaco",
        "Reunion",
        "North Macedonia",
        "Honduras",
        "Barbados",
        "Palestine",
        "US Virgin Islands"
    ],
    "C": [
        "Gambia",
        "Mongolia",
        "Martinique",
        "Grenada",
        "Belize",
        "Cayman Islands",
        "North Mariana Islands",
        "Saint Lucia",
        "Trinidad & Tobago",
        "Seychelles",
        "Benin",
        "Brunei",
        "Bangladesh",
        "Bhutan",
        "Guyana",
        "British Virgin Islands",
        "Antigua & Barbuda",
        "Haiti",
        "Bermuda",
        "Venezuela",
        "French Polynesia",
        "Papua New Guinea",
        "Rep. Modolva",
        "Samoa",
        "Cook Islands",
        "Burkina Faso",
        "New Caledonia",
        "Vanuatu",
        "St. Kitts & Nevis",
        "San Marino",
        "Anguilla",
        "Palau",
        "Dominica",
        "St. Vinicent & Grenedines",
        "Liechtenstein",
        "Timor Leste",
        "Tonga",
        "French Guiana",
        "Solomon Islands",
        "Comoros",
        "American Samoa",
        "Federated States of Micronesia",
        "Mali",
        "Montserrat",
        "Niue",
        "Kiribati",
        "Marshall Islands",
        "Tuvalu",
    ],
    "D": [
        "Afghanistan",
        "Botswana",
        "Burundi",
        "Central African Republic",
        "Congo",
        "Djibouti",
        "Ethiopia",
        "Guinea",
        "Guinea-Bissau",
        "Iraq",
        "Ireland",
        "Liberia",
        "Libya",
        "Malawi",
        "Mauritania",
        "Myanmar",
        "Pakistan",
        "Sao Tome & Principe",
        "Sudan",
        "Suriname",
        "Zambia",
        "Somalia",
        "Chad",
        "Sierra Leone",
        "Niger",
        "Kuwait",
        "Angola",
        "Cameroon",
        "Madagascar",
    ],
    "H": [
        "Canada",
    ]
}

TIER_PROBABILITY = {
    "SS": 0.95, #0.05
    "S": 0.85, #0.1
    "A": 0.70, #0.15
    "B": 0.20, #0.5
    "C": 0.06, #0.14
    "D":0.05, # 0.01
    "H": 0.00,
}

COUNTRY_CATEGORIES = {
    "France": {EUROPE},
    "Spain": {EUROPE},
    "United States": {NORTH_AMERICA},
    "China": {EAST_ASIA},
    "Italy": {EUROPE},
    "Türkiye": {OTHER_ASIA},
    "Mexico": {NORTH_AMERICA},
    "Thailand": {SOUTHEAST_ASIA},
    "United Kingdom":{EUROPE},
    "Germany":{EUROPE},
    "Denmark":{EUROPE},
    "Japan":{EAST_ASIA, ISLAND},
    "Greece":{EUROPE},
    "Malaysia":{SOUTHEAST_ASIA},
    "Portugal":{EUROPE},
    "Russia":{EUROPE},
    "Hong Kong":{EAST_ASIA, ISLAND},
    "Austria": {EUROPE},
    "UAE": {OTHER_ASIA},
    "Poland": {EUROPE},
    "Netherlands":{EUROPE},
    "Singapore":{SOUTHEAST_ASIA, ISLAND},
    "Macao":{EAST_ASIA},
    "Vietnam":{SOUTHEAST_ASIA},
    "India":{OTHER_ASIA},
    "Saudi Arabia":{OTHER_ASIA},
    "Republic of Korea":{EAST_ASIA},
    "Croatia":{EUROPE},
    "Hungary":{EUROPE},
    "Indonesia":{SOUTHEAST_ASIA, ISLAND},
    "Czech Republic":{EUROPE},
    "Ukraine":{EUROPE},
    "Egypt":{AFRICA},
    "Morrocco":{AFRICA},
    "Romania":{EUROPE},
    "Bulgaria":{EUROPE},
    "Taiwan":{EAST_ASIA, ISLAND},
    "Belarus":{EUROPE},
    "Switzerland":{EUROPE},
    "South Africa":{AFRICA},
    "Australia":{OCEANIA, ISLAND},
    "Tunisia":{AFRICA},
    "Belgium":{EUROPE},
    "Iran":{OTHER_ASIA},
    "Kazakhstan":{OTHER_ASIA},
    "Kyrgyzstan":{OTHER_ASIA},
    "Philippines":{SOUTHEAST_ASIA, ISLAND},
    "Argentina":{SOUTH_AMERICA},
    "Uzbekistan":{OTHER_ASIA},
    "Cambodia":{SOUTHEAST_ASIA},
    "Dominican Republic":{CARRIBEAN, ISLAND},
    "Slovakia": {EUROPE},
    "Brazil": {SOUTH_AMERICA},
    "Albania":{EUROPE},
    "Nigeria":{AFRICA},
    "Georgia":{EUROPE},
    "Sweden":{EUROPE},
    "Laos":{SOUTHEAST_ASIA},
    "Slovenia":{EUROPE},
    "Israel":{OTHER_ASIA},
    "Chile":{SOUTH_AMERICA},
    "Jordan":{OTHER_ASIA},
    "Peru":{SOUTH_AMERICA},
    "Cuba":{CARRIBEAN, ISLAND},
    "Colombia":{SOUTH_AMERICA},
    "Norway":{EUROPE},
    "Cyprus":{EUROPE, ISLAND, OTHER_ASIA},
    "New Zealand":{OCEANIA, ISLAND},
    "Bahrain": {OTHER_ASIA},
    "Uruguay": {SOUTH_AMERICA},
    "Estonia": {EUROPE}, 
    "Puerto Rico":{CARRIBEAN, ISLAND},
    "Costa Rica": {NORTH_AMERICA},
    "Andorra": {EUROPE},
    "Finland":{EUROPE},
    "Lithuania":{EUROPE},
    "Azerbaijan":{OTHER_ASIA},
    "Malta": {EUROPE, ISLAND},
    "Jamaica": {CARRIBEAN, ISLAND},
    "Montenegro": {EUROPE},
    "Oman":{OTHER_ASIA},
    "Syria":{OTHER_ASIA},
    "Algeria":{AFRICA},
    "Zimbabwe":{AFRICA},
    "Qatar":{OTHER_ASIA},
    "Ecuador":{SOUTH_AMERICA},
    "Cote d'Ivoire":{AFRICA},
    "Mozambique":{AFRICA},
    "Iceland":{EUROPE, ISLAND},
    "Lebanon":{OTHER_ASIA},
    "Latvia":{EUROPE},
    "Sri Lanka":{OTHER_ASIA, ISLAND},
    "Armenia":{OTHER_ASIA},
    "Kenya":{AFRICA},
    "Bahamas":{CARRIBEAN, ISLAND},
    "El Salvador":{NORTH_AMERICA},
    "Panama":{NORTH_AMERICA},
    "Guatemala":{NORTH_AMERICA},
    "Maldives": {OTHER_ASIA, ISLAND},
    "Guam": {OCEANIA, ISLAND},
    "Rwanda": {AFRICA},
    "Serbia": {EUROPE},
    "Turks & Caicos (British Overseas Territory)": {CARRIBEAN, ISLAND},
    "Namibia":{AFRICA},
    "Uganda": {AFRICA},
    "Tanzania": {AFRICA},
    "Mauritius": {AFRICA, ISLAND},
    "Nicaragua": {NORTH_AMERICA},
    "Tajikistan": {OTHER_ASIA},
    "Bolivia": {SOUTH_AMERICA},
    "Paraguay": {SOUTH_AMERICA},
    "Bosnia & Herzegovinia": {EUROPE},
    "Nepal":{EAST_ASIA},
    "Eswatini":{AFRICA},
    "Lesotho": {AFRICA},
    "Aruba (Constituent Country of the Kingdom of the Netherlands)":{SOUTH_AMERICA, ISLAND},
    "Ghana": {AFRICA},
    "Luxembourg": {EUROPE},
    "Fiji":{OCEANIA, ISLAND},
    "Togo":{OCEANIA, ISLAND},
    "Cabo Verde":{AFRICA, ISLAND},
    "Monaco":{EUROPE},
    "Reunion":{AFRICA, ISLAND},
    "North Macedonia":{EUROPE},
    "Honduras":{NORTH_AMERICA},
    "Barbados":{CARRIBEAN, ISLAND},
    "Palestine":{OTHER_ASIA},
    "US Virgin Islands": {CARRIBEAN, ISLAND},
    "Gambia": {AFRICA},
    "Mongolia": {EAST_ASIA},
    "Martinique": {CARRIBEAN, ISLAND},
    "Grenada": {CARRIBEAN, ISLAND},
    "Belize": {NORTH_AMERICA},
    "Cayman Islands": {CARRIBEAN, ISLAND},
    "North Mariana Islands":{OCEANIA, ISLAND},
    "Saint Lucia": {CARRIBEAN, ISLAND},
    "Trinidad & Tobago": {CARRIBEAN, ISLAND},
    "Seychelles": {OTHER_ASIA, ISLAND},
    "Benin":{AFRICA},
    "Brunei":{SOUTHEAST_ASIA},
    "Bangladesh":{OTHER_ASIA},
    "Bhutan":{EAST_ASIA},
    "Guyana":{SOUTH_AMERICA},
    "British Virgin Islands":{CARRIBEAN, ISLAND},
    "Antigua & Barbuda": {CARRIBEAN, ISLAND},
    "Haiti": {CARRIBEAN, ISLAND},
    "Bermuda": {CARRIBEAN, ISLAND},
    "Venezuela": {SOUTH_AMERICA},
    "French Polynesia": {OCEANIA, ISLAND},
    "Papua New Guinea": {OCEANIA},
    "Rep. Modolva": {EUROPE},
    "Samoa":{OCEANIA, ISLAND},
    "Cook Islands": {OCEANIA, ISLAND},
    "Burkina Faso": {AFRICA},
    "New Caledonia": {OCEANIA, ISLAND},
    "Vanuatu": {OCEANIA, ISLAND},
    "St. Kitts & Nevis": {CARRIBEAN, ISLAND},
    "San Marino": {EUROPE},
    "Anguilla": {CARRIBEAN, ISLAND},
    "Palau": {OCEANIA,ISLAND},
    "Dominica": {CARRIBEAN, ISLAND},
    "St. Vinicent & Grenedines": {CARRIBEAN, ISLAND},
    "Liechtenstein": {EUROPE},
    "Timor Leste": {SOUTHEAST_ASIA, ISLAND},
    "Tonga": {OCEANIA, ISLAND},
    "French Guiana": {SOUTH_AMERICA},
    "Solomon Islands": {OCEANIA, ISLAND},
    "Comoros": {AFRICA, ISLAND},
    "American Samoa": {OCEANIA, ISLAND},
    "Federated States of Micronesia": {OCEANIA, ISLAND},
    "Mali": {AFRICA},
    "Montserrat":{CARRIBEAN, ISLAND},
    "Niue": {OCEANIA, ISLAND},
    "Kiribati": {OCEANIA, ISLAND},
    "Marshall Islands": {OCEANIA, ISLAND},
    "Tuvalu": {OCEANIA, ISLAND},
    "Afghanistan":{OTHER_ASIA},
    "Botswana": {AFRICA},
    "Burundi":{AFRICA},
    "Central African Republic": {AFRICA},
    "Congo": {AFRICA},
    "Djibouti": {OTHER_ASIA},
    "Ethiopia": {AFRICA},
    "Guinea":{AFRICA},
    "Guinea-Bissau":{AFRICA},
    "Iraq":{OTHER_ASIA},
    "Ireland":{EUROPE},
    "Liberia":{AFRICA},
    "Libya":{AFRICA},
    "Malawi":{AFRICA},
    "Mauritania":{AFRICA},
    "Myanmar":{SOUTHEAST_ASIA},
    "Pakistan":{OTHER_ASIA},
    "Sao Tome & Principe": {AFRICA, ISLAND},
    "Sudan": {AFRICA},
    "Suriname":{SOUTH_AMERICA},
    "Zambia":{AFRICA},
    "Somalia":{AFRICA},
    "Chad":{AFRICA},
    "Sierra Leone":{AFRICA},
    "Niger":{AFRICA},
    "Kuwait":{OTHER_ASIA},
    "Angola":{AFRICA},
    "Cameroon":{AFRICA},
    "Madagascar":{AFRICA, ISLAND},
    "Canada": {NORTH_AMERICA, HOME}

}